### ISSUE TITLE
Single sign-on (SSO) with OIDC

### ISSUE THREAD

**Issue by erlend-sh** [raffomania/linkblocks#46]
For easy onboarding, users should be able to log in with their existing identity provider, such as GitHub, Google etc., but also independent options thanks to the likes of [Rauthy](https://github.com/sebadob/rauthy/).

Relevant crates:
https://crates.io/crates/openidconnect
https://crates.io/crates/axum-oidc

**Comment by raffomania** [comment]
Fixed in #51
