### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by retiolus** [raffomania/linkblocks#47]
Hi, didn't find a LICENSE in this repo, if there is one, would you tell use where it is, please? If not, could you add one?

Thanks

**Comment by erlend-sh** [comment]
I asked the same thing via chat and it’s going to be AGPL.

**Comment by raffomania** [comment]
Thanks for the issue! I've been meaning to do this for a while, but was preoccupied with securing some funding for further linkblocks development. [I've just added a license to the repo](https://github.com/raffomania/linkblocks/pull/50).
